fixtures:
  repositories:
    apache:  'git://github.com/puppetlabs/puppetlabs-apache.git'
    concat:  'git://github.com/puppetlabs/puppetlabs-concat.git'
    inifile: 'git://github.com/puppetlabs/puppetlabs-inifile.git'
    stdlib:  'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    vcsrepo: 'git://github.com/puppetlabs/puppetlabs-vcsrepo.git'

  symlinks:
    icingaweb2: "#{source_dir}"

